# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ alan-dev ]
  pull_request:
    branches: [ alan-dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: alan-dev
          
      - uses: gradle/gradle-build-action@v2.1.3
      - uses: actions/setup-java@v2
        with:
          java-version: 8.0.322+6
          distribution: 'adopt'
        

      # Runs a single command using the runners shell
      - name: Salutation
        run: echo Hello, world actions!

      # Runs a set of commands using the runners shell
      - name: print some text about action 
        run: |
          echo BUILD
          echo TEST

      - name: Test and buid
        run: |
          gradle build
          gradle jacocoTestReport
          
      - name: SonarCloud Scan
        run:
          gradle sonarqube
          
  cd:
      runs-on: ubuntu-latest
      needs: ci
  
      steps:
        - uses: actions/checkout@v1
        - name: Docker login
          run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
        - name: Build
          run: docker build -t back .
        - name: Tags
          run: |
            docker tag back ${{ secrets.DOCKER_USER }}/ratingUPGRADE:${{ github.sha }}
            docker tag back ${{ secrets.DOCKER_USER }}/ratingUPGRADE:latest
        - name: Push
          run: |
            docker push ${{ secrets.DOCKER_USER }}/ratingUPGRADE:${{ github.sha }}
            docker push ${{ secrets.DOCKER_USER }}/ratingUPGRADE:latest
    
